name: Check attack surface against Route53

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # every Monday at 9am

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install # Install all dependencies
    
      - name: Retrieve the Google credentials and decode them to a file
        env:
          GOOGLE_SERVICE_ACCOUNT_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT_BASE64 | base64 --decode > google_service_account_credentials.json

      - name: Check attack surface changes
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run ./list_attack_surface_changes.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GOOGLE_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PROJECT_ID }}
          GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
          GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_ID }}
          GOOGLE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}
